import moment from 'moment';
export const data = [
  {
    key: '1',
    name: '胡彦斌',
    count: 1432,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 1,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '2',
    name: '胡小斌',
    count: 4221,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 2,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '3',
    name: '胡大彦',
    count: 873,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 3,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '4',
    name: '胡中',
    count: 7362,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 4,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '5',
    name: '胡碟',
    count: 12,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 3,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '6',
    name: '胡恼',
    count: 7399,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 1,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '7',
    name: '胡锁',
    count: 3782,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 3,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '8',
    name: '胡八一',
    count: 9382,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 4,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '9',
    name: '胡北溪',
    count: 8822,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 2,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '10',
    name: '胡东',
    count: 7632,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 2,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '11',
    name: '胡前',
    count: 7763,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 4,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
  {
    key: '12',
    name: '胡攀',
    count: 198,
    type: 'jt',
    desc: '西湖区湖底公园1号',
    status: 3,
    time: moment(),
    createAt: 'admin',
    updateAt: 'admin',
  },
];
