import moment from 'moment';
export const data = [
  {
    key: '1',
    name: '胡彦斌',
    age: 1,
    type: 'yk',
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '2',
    name: '胡彦祖',
    type: 'gly',
    age: 2,
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '3',
    name: '胡彦斌',
    age: 3,
    type: 'yk',
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '4',
    name: '胡彦祖',
    type: 'gly',
    age: 4,
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '5',
    name: '胡彦斌',
    age: 5,
    type: 'yk',
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '6',
    name: '胡彦祖',
    type: 'gly',
    age: 6,
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '7',
    name: '胡彦斌',
    age: 7,
    type: 'yk',
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '8',
    name: '胡彦祖',
    type: 'gly',
    age: 8,
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '9',
    name: '胡彦斌',
    age: 9,
    type: 'yk',
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '10',
    name: '胡彦祖',
    type: 'gly',
    age: 10,
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '11',
    name: '胡彦斌',
    age: 11,
    type: 'yk',
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
  {
    key: '12',
    name: '胡彦祖',
    type: 'gly',
    age: 12,
    address: '西湖区湖底公园1号',
    createTime: moment(),
    createAt: '创建人',
    updateTime: moment(),
    updateAt: '创建人',
  },
];

export const roleType = [
  {
    title: '管理员',
    value: 'gly',
  },
  {
    title: '游客',
    value: 'yk',
  },
  {
    title: '超级管理员',
    value: 'cjgly',
  },
];
